#!/bin/bash

cat <<EOF
# Cloudflare
# Generated by scripts/generate-cloudflare-config.sh

real_ip_header  CF-Connecting-IP;
log_format      cloudflare '\$remote_addr - \$remote_user [\$time_local] "\$request" \$status \$body_bytes_sent "\$http_referer" "\$http_user_agent" \$http_cf_ray \$http_cf_connecting_ip';

# https://www.cloudflare.com/ips-v4/
$(curl -s https://www.cloudflare.com/ips-v4/ | xargs -I {} echo "set_real_ip_from {};")

# https://www.cloudflare.com/ips-v6/
$(curl -s https://www.cloudflare.com/ips-v6/ | xargs -I {} echo "set_real_ip_from {};")
EOF
