name: Release

on:
  push:
    branches:
      - v1

  # Build daily on 00:00 UTC
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    # continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          - stable-alpine
          - mainline
          - mainline-alpine
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: chocolatefrappe/nginx-reverse-proxy
          tags: type=raw,value=${{ matrix.version }}

      - name: Build and push
        uses: docker/bake-action@v3
        env:
          NGINX_VERSION: ${{ matrix.version }}
        with:
          files: |
            docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Docker Metadata Summary
        uses: dockerbakery/docker-metadata-summary@v1
