name: Release

on:
  push:
    branches:
      - v1

  # Build daily on 00:00 UTC
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  canonical:
    uses: ./.github/workflows/canonical.yml
    secrets: inherit

  versioned:
    uses: ./.github/workflows/versioned.yml
    secrets: inherit
