name: Release

on:
  workflow_call:
  push:
    branches:
      - v1

  # Build daily on 00:00 UTC
  schedule:
    - cron: '0 0 * * SUN'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  canonical:
    uses: ./.github/workflows/release-canonical.yml
    secrets: inherit

  versioned:
    uses: ./.github/workflows/release-versioned.yml
    secrets: inherit
